### ISSUE TITLE
Lint reports a few errors

### ISSUE THREAD

**Issue by drgrigg** [alphgal/willa-cather_the-song-of-the-lark#3]
If you run `se lint .` again you'll see it throws up three things for you to have a look at.

In local.css you don't need the class epub-type-dedication. Instead, have a look at the manual for how to do the CSS for dedication pages: https://standardebooks.org/manual/1.6.1/single-page#7.3

**Comment by alphgal** [comment]
Hmm. I tried to include the CSS shown in the manual but that threw up an error ("CSS class found in XHTML, but not in local.css.") The error doesn't occur with the coding that I have used (which I copied from another ebook on Standard Ebooks).

As for "V-shaped", as far as I could figure out, that is the correct coding? It can't have either spaces or a period.

Quote marks fixed.

**Comment by drgrigg** [comment]
Search for `class="epub-type-dedication"` and remove all instances in your body text.

**Comment by alphgal** [comment]
Aha! Now I understand. Fixed now!

**Comment by drgrigg** [comment]
So does lint run clean?

**Comment by alphgal** [comment]
Yes. Just the "V-shaped" manual review is flagged now.

**Comment by drgrigg** [comment]
OK, you should remove the `<abbr>` tag altogether. It's not an abbreviation, just the description of a shape. Just leave it as plain `V-shaped`.

**Comment by drgrigg** [comment]
Semanticate will want to make that `<span epub:type="z3998:roman">V</span>, but don't let it!

**Comment by alphgal** [comment]
OK. Fixed! (And keeping away from semanticate.)
