### ISSUE TITLE
In the colophon, your own name needs to be placed in tags

### ISSUE THREAD

**Issue by drgrigg** [alphgal/willa-cather_the-song-of-the-lark#4]
If you have a URL you want to link people to, you should place it within an `<a>` tag like this example:

`<a href="YOUR URL">Hui-chang Wang</a>`

or if not, just within a `<b>` tag like the transcribers:

`<b class="name">Hui-chang Wang</b>`

**Comment by alphgal** [comment]
Thanks. Fixed.
