### ISSUE TITLE
Need to run typogrify again and review changes

### ISSUE THREAD

**Issue by drgrigg** [alphgal/willa-cather_the-song-of-the-lark#5]
Typogrify makes a lot of changes. On a quick look, most if not all should be accepted (including fixing some straight, non-curly quotes)

**Comment by alphgal** [comment]
Thanks David. I've been through all of these and they look correct. This work has a lot of quotes within quotes and also a few s' possessives, so that is why typogrify brings up errors. Unless there is something I'm missing?

**Comment by drgrigg** [comment]
Typogrify is almost always correct. A number of the changes it wants to make are to do with putting in hair-spaces before or after dashes (you should accept these) 

It also looks to me as if it's changing straight quotes to curly quotes, which again you should accept. For example, in the colophon, you have: `The Shepherd's Star`, which should be `The Shepherd’s Star` with a single rquo as the apostrophe, not a straight apostrophe. Typogrify will sort this out for you.

In chapter 3-2 there's a phrase which seems to have em-dashes in it: without hunting up the page scans I'm not sure if that's what you want:  Dans⁠—⁠nos⁠ a⁠-lár⁠—mes! If it's correct, then allow typogrify to put in the hair-spaces.

**Comment by drgrigg** [comment]
So far as i can see with your project you can't really go wrong just running se typogrify and accepting everything.

**Comment by alphgal** [comment]
OK. I ran se typogrify it didn't ask me to accept anything. It just ran and returned a prompt. Anyway, I will assume it has fixed everything. Not sure why my system doesn't throw up the same things yours does. I think this happened to me last time I did an ebook. I have a Mac - maybe that's the difference?

**Comment by drgrigg** [comment]
I'm on a Mac, too. You shouldn't expect typogrify to report anything, it just makes changes. I was looking at those changes via `git difftool` which in my case invokes an app called Kaleidoscope, which lets me see exactly what has changed before and after typogrify.

**Comment by alphgal** [comment]
Aha! OK. I'll have a look at how to use git difftool in future. Thanks for all your help!
