### ISSUE TITLE
Build errors in content.opf

### ISSUE THREAD

**Issue by drgrigg** [alphgal/willa-cather_the-song-of-the-lark#7]
If you run `se build .`  you'll get shown a bunch of errors. This isn't your fault.  The rules changed while you were working on this project. The strict epub spec says that we can't define more than one role to any entity in the metadata, so we've implemented our own version, se:role. 

Run build and it will show you where it is throwing errors regarding this. Check out the manual at https://standardebooks.org/manual/1.6.1/single-page#9.10.5 for how to deal with roles in content.opf under the new methods.

Have a look at the source for some other recently released SE productions and you'll quickly get the idea.

**Comment by alphgal** [comment]
Thanks David. Strangely, when I ran se build again no errors appeared (I have upgraded to the latest version of standardebooks etc.). But I have manually corrected the producer roles in content.opf now, so I hope that that fixes it. I can't test it as se build still doesn't produce any errors.

**Comment by drgrigg** [comment]
Well if it's not producing errors all must be well, I guess.
